image: "python:3.8-slim"

before_script:
  - python3 --version

stages:
  - analysis
  - test

test:
  stage: test
  script:
    - python3 -m venv venv/
    - source venv/bin/activate
    - pip install django
    - python project/manage.py makemigrations
    - python project/manage.py migrate
    - python project/manage.py test


pep8:
  stage: analysis
  script:
    - pycodestyle project/cms/views.py
